### ISSUE TITLE
Typo in tight electron iso

### ISSUE THREAD

**Issue by artlbv** [jkiesele/PhaseTwoAnalysis#16]
In here: https://github.com/jkiesele/PhaseTwoAnalysis/blob/b6c3b34897ac02b50095bb7d60f4fa3921a416c8/NTupler/plugins/MiniFromPat.cc#L569-L571

`ev_.te_relIso[ev_.nle]` should be `ev_.te_relIso[ev_.nte]` (ev_.te_relIso[ev_.n**t**e])

**Comment by jkiesele** [comment]
thanks for noticing
fixed
